apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: stackdriver-exporter
  name: stackdriver-exporter
spec:
  selector:
    matchLabels:
        app: stackdriver-exporter
  endpoints:
    - port: metrics
      interval: 30s
