apiVersion: v1
kind: Service
metadata:
  name: stackdriver-exporter
  labels:
    app: stackdriver-exporter
spec:
  type: ClusterIP
  selector:
    app: stackdriver-exporter
  ports:
    - name: metrics
      port: 9255
      targetPort: 9255
      protocol: TCP
