apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: theodolite-http-bridge
  name: theodolite-http-bridge
spec:
  selector:
    matchLabels:
        app: theodolite-http-bridge
  endpoints:
    - port: http-endpoint
      interval: 10s
