apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-aggregation
spec:
  selector:
    matchLabels:
      app: titan-ccp-aggregation
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-aggregation
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: uc1-beam-samza
          image: ghcr.io/cau-se/theodolite-uc1-beam-samza:firestore-test-latest
          command:
            - "/uc1-beam-samza/bin/uc1-beam-samza"
            - "--configFilePath=samza-standalone.properties"
            - "--samzaExecutionEnvironment=STANDALONE"
            - "--maxSourceParallelism=1024"
            - "--enableMetrics=false"
            - "--systemBufferSize=1000"
            - "--configOverride={\"job.coordinator.zk.connect\":\"theodolite-kafka-zoo-entrance:2181\"}"
          env:
            - name: SAMZA_JOB_COORDINATOR_ZK_CONNECT
              value: "theodolite-kafka-zoo-entrance:2181"
            - name: SAMZA_SYSTEMS_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: SAMZA_SYSTEMS_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: MAX_SOURCE_PARALLELISM
              value: "1024"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://theodolite-cp-schema-registry:8081"
            - name: COMMIT_INTERVAL_MS # Set as default for the applications
              value: "100"
            - name: "SINK_TYPE"
              value: "firestore"
            - name: "SINK_FIRESTORE_COLLECTION"
              value: "activepowerrecords"
            - name: "SINK_FIRESTORE_HINT_MAX_WORKERS"
              value: "1"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          resources:
            limits:
              memory: 3Gi
              cpu: 950m
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-key