apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc3-beam-flink-http-aws-4x4
spec:
  benchmark: "uc3-beam-flink-http-aws"
  load:
    loadType: "NumSensors"
    loadValues: [1200]
  resources:
    resourceType: "Instances"
    resourceValues: [7, 8, 9]
  slos:
    - sloType: "lag trend ratio"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        #threshold: 100
        ratio: 0.025
        externalSloUrl: "http://localhost:80/evaluate-slope"
        consumerGroup: theodolite-uc3-application
        warmup: 120 # in seconds
  execution:
    duration: 300 # in seconds
    loadGenerationDelay: 30
    repetitions: 1
    strategy: "LinearSearch"
    restrictions:
      - "LowerBound"
  configOverrides:
  - patcher:
      type: "EnvVarPatcher"
      resource: "terraform-deployment-aws.yaml"
      properties:
        container: "terraform"
        variableName: "HTTP_URL"
    value: "http://internal-a2dfdd18e3e744d0d9d6af70cde43a7b-712175647.eu-central-1.elb.amazonaws.com:8080"
  - patcher:
      type: "EnvVarPatcher"
      resource: "terraform-deployment-aws.yaml"
      properties:
        container: "terraform"
        variableName: "AWS_SUBNET_ID"
    value: "subnet-0668fbd516b3cd875"
