apiVersion: theodolite.com/v1
kind: execution
metadata:
  name: uc3-beam-flink-pubsub-4x4
spec:
  benchmark: "uc3-beam-flink-pubsub"
  load:
    loadType: "NumSensors"
    loadValues: [1000, 1100, 1200]
  resources:
    resourceType: "Instances"
    resourceValues: [7, 8, 9, 10, 11]
  slos:
    - sloType: "lag trend ratio"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0 # in seconds
      properties:
        promQLQuery: "sum by(subscription_id) (stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_num_unacked_messages_by_region >= 0)"
        ratio: 0.025
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 300 # in seconds
  execution:
    duration: 420 # in seconds
    loadGenerationDelay: 0
    repetitions: 1
    strategy: "LinearSearch"
    restrictions:
      - "LowerBound"
  configOverrides:
  - patcher:
      type: "EnvVarPatcher"
      resource: "terraform-deployment-gcp.yaml"
      properties:
        container: "terraform"
        variableName: "TARGET"
    value: "pubsub"
