apiVersion: theodolite.com/v1
kind: benchmark
metadata:
  name: uc1-beam-flink-http-aws
spec:
  sut:
    resources:
      - configMap:
          name: "http-bridge"
          files:
          - "input-topic.yaml"
          - "http-bridge-deployment.yaml"
          - "http-bridge-service.yaml"
          # - "http-bridge-service-monitor.yaml"
      - configMap:
          name: "uc1-beam-flink-http"
          files:
          - "flink-configuration-configmap.yaml"
          - "taskmanager-deployment.yaml"
          - "taskmanager-service.yaml"
          - "service-monitor.yaml"
          - "jobmanager-service.yaml"
          - "jobmanager-deployment.yaml"
          # - "jobmanager-rest-service.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "terraform-load-generator-aws"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "taskmanager-deployment.yaml"
        - type: "EnvVarPatcher"
          resource: "jobmanager-deployment.yaml"
          properties:
            container: "jobmanager"
            variableName: "PARALLELISM"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "terraform-deployment-aws.yaml"
          properties:
            container: "terraform"
            variableName: "LOAD_INTENSITY"
