apiVersion: apps/v1
kind: Deployment
metadata:
  name: theodolite-uc3-beam-dataflow-submitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theodolite-uc3-beam-dataflow
      component: submitter
  template:
    metadata:
      labels:
        app: theodolite-uc3-beam-dataflow
        component: submitter
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: dataflow-submitter
          image: ghcr.io/cau-se/theodolite-uc3-beam-dataflow:firestore-test-latest
          imagePullPolicy: Always
          args:
           - "/uc3-beam-dataflow/bin/uc3-beam-dataflow"
           - "--region=europe-west3"
           - "--streaming=true"
           - "--project=$(GCP_PROJECT)"
           - "--workerMachineType=$(WORKER_MACHINE_TYPE)"
           - "--numWorkers=$(NUM_WORKERS)"
           - "--autoscalingAlgorithm=NONE"
          env:
            - name: "NUM_WORKERS"
              value: "1"
            - name: "WORKER_MACHINE_TYPE"
              value: "e2-standard-4"
            - name: "AGGREGATION_DURATION_SECONDS"
              value: "30"
            - name: "AGGREGATION_ADVANCE_SECONDS"
              value: "3"
            - name: GCP_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: project
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: SOURCE_PUBSUB_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: project
            - name: "SOURCE_PUBSUB_SUBSCRIPTION"
              value: "input-subscription"
            - name: "SOURCE_TYPE"
              value: "pubsub"
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-key
